openapi: 3.0.3
info:
  title: Game Recommendations API
  version: 1.0.0
  description: An API for game recommendations and saving starred games

servers:
  - url: http://127.0.0.1:3001/

paths:
  /games:
    get:
      summary: Get a list of games
      operationId: getGames
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Game"
  /games/{gameId}:
    get:
      summary: Get a game by ID
      operationId: getGameById
      parameters:
        - name: gameId
          in: path
          description: ID of the game to retrieve
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Game"
        "404":
          description: Game not found

  /recommendations:
    post:
      summary: Create a game recommendation
      operationId: createRecommendation
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/recommendation"
      responses:
        "201":
          description: Created
        "400":
          description: Invalid request payload

  /recommendations/starred:
    get:
      summary: Get starred game recommendations
      operationId: getStarredRecommendations
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Game"

components:
  schemas:
    Game:
      type: object
      properties:
        uuid:
          type: string
        title:
          type: string
        genre:
          type: string
        ageRating:
          type: number
        starred:
          type: boolean
    recommendation:
      type: object
      properties:
        gameId:
          type: string
        dateRecommended:
          type: string
